# -*- coding: utf-8 -*-
"""EntrenamientoModeloMotor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1snNaPHzRg0mC9ASbol51Xo0JCBo7Mev5

# Import necesarios para el analisis de datos y entrenamiento de modelos de Inteligencia Artificial
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.semi_supervised import SelfTrainingClassifier
from sklearn.cluster import KMeans
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.neural_network import BernoulliRBM
from sklearn.utils.class_weight import compute_sample_weight

"""Cargamos el dataframe que usaremos para entrenar nuestros modelos, con df.head() comprobamos que se hayan cargado bien los datos."""

df = pd.read_csv("/content/engine_data.csv")
df.head()

"""Tambien podemos comprobar informacion de las columnas de nuestro dataframe"""

df.info()

"""# Analisis de datos"""

type_ef = df['Engine Condition'].value_counts().reset_index()
type_ef.columns = ['Engine Condition', 'Count']

sns.barplot(x='Engine Condition', y='Count', data=type_ef)

plt.title('Type of Engine Condition')
plt.xlabel('Type')
plt.ylabel('Count')
plt.show()

"""Vemos que tenemosunos casi 8000 ejemplos de fallos y unos 12000 ejemplos de no fallos, suficiente representativo.
# **Box plot**
"""

numerical_df = df.select_dtypes(include=['float64', 'int64'])

numerical_df.head()

"""Con las Box plot podemos observar algunos outliers un poco exagerados, por ejemplo en coolant temp, que pueden ser errores de medicion y vendria bien descartarlos pero demomento vamos a seguir analizando los datos."""

numnerical_columns = ['Lub oil pressure','Fuel pressure','Coolant pressure','lub oil temp','Coolant temp']

df_numerical = df[numnerical_columns]

plt.figure(figsize=(12, 8))
sns.boxplot(data=df_numerical)

plt.title('Box Plot of Numerical Columns')
plt.xlabel('Columns')
plt.ylabel('Values')
plt.show()

df_numerical_2 = df["Engine rpm"]

plt.figure(figsize=(12, 8))
sns.boxplot(data=df_numerical_2)

plt.title('Box Plot of Numerical Columns')
plt.xlabel('Columns')
plt.ylabel('Values')
plt.show()

numerical_columns = ['Engine rpm','Lub oil pressure','Fuel pressure','Coolant pressure','lub oil temp','Coolant temp']
for column in numerical_columns:
  plt.figure(figsize=(12, 8))
  sns.boxplot(data=df[column])
  plt.title(f'Box Plot of {column}')
  plt.xlabel('Values')
  plt.show()

"""Vamos a eliminar los outliers ya que pueden confundir a nuestros modelos."""

for column in df[numerical_columns]:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    print(f"{column} - Q1: {Q1}, Q3: {Q3}, IQR: {IQR}")

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

numerical_columns = ['Engine rpm','Lub oil pressure','Fuel pressure','Coolant pressure','lub oil temp','Coolant temp']
for column in numerical_columns:
  plt.figure(figsize=(12, 8))
  sns.boxplot(data=df[column])
  plt.title(f'Box Plot of {column}')
  plt.xlabel('Values')
  plt.show()

"""Con esto ya no tenemos outliers demasiado exagerados.Tambien podemos ver histogramas con el numero de frecuencia para distintos rangos de valores."""

for feat in numerical_columns:
    plt.figure(figsize=(8, 6))  # Set the figure size
    plt.hist(df[feat], bins=20, color='skyblue', edgecolor='black')
    plt.title(f'Histogram for {feat}')  # Add title
    plt.xlabel(feat)  # Label x-axis
    plt.ylabel('Frequency')  # Label y-axis
    plt.show()

"""# Comenzamos con la preparacion de los datos"""

X = df.drop('Engine Condition', axis=1)
y = df['Engine Condition']

print(X.head())
print("------------------------------")
print(y.head())

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training Features (X_train):", X_train.shape)
print("Testing Features (X_test):", X_test.shape)
print("Training Target (y_train):", y_train.shape)
print("Testing Target (y_test):", y_test.shape)

"""Vamos a probar a entrenar modelos con varios tipos de datos, el primero va a ser con datos sin nigun tipo de procesamiento o normalizado."""

# Initialize the Logistic Regression model
LogisticRegression_model = LogisticRegression(random_state=42, max_iter=10000)

# Train the model on the balanced training data
LogisticRegression_model.fit(X_train, y_train)

# Predict on the test data
y_pred = LogisticRegression_model.predict(X_test)

# Evaluate the model
print("LR Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nAccuracy Score:", accuracy_score(y_test, y_pred))

plt.figure(figsize=(8, 6))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

RandomForest_model = RandomForestClassifier(random_state=42)

RandomForest_model.fit(X_train, y_train)

y_pred_rf = RandomForest_model.predict(X_test)

print("Random Forest Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

print("\nRandom Forest Classification Report:")
print(classification_report(y_test, y_pred_rf))

print("\nRandom Forest Accuracy Score:", accuracy_score(y_test, y_pred_rf))

plt.figure(figsize=(8, 6))
sns.heatmap(confusion_matrix(y_test, y_pred_rf), annot=True, fmt='d', cmap="Blues")
plt.title('Random Forest Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

DecisionTree_model = DecisionTreeClassifier(random_state=42)

DecisionTree_model.fit(X_train, y_train)

y_pred_dt = DecisionTree_model.predict(X_test)

print("Decision Tree Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))

print("\nDecision Tree Classification Report:")
print(classification_report(y_test, y_pred_dt))

print("\nDecision Tree Accuracy Score:", accuracy_score(y_test, y_pred_dt))

plt.figure(figsize=(8, 6))
sns.heatmap(confusion_matrix(y_test, y_pred_dt), annot=True, fmt='d', cmap='Blues')
plt.title('Decision Tree Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# Initialize a base estimator for SelfTrainingClassifier
base_estimator = DecisionTreeClassifier(random_state=42)

# Initialize the SelfTrainingClassifier
SelfTraining_model = SelfTrainingClassifier(estimator=base_estimator)

# Train the model
SelfTraining_model.fit(X_train, y_train)

# Predict on the test data
y_pred_st = SelfTraining_model.predict(X_test)

# Evaluate the model
print("SelfTrainingClassifier Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_st))

print("\nSelfTrainingClassifier Classification Report:")
print(classification_report(y_test, y_pred_st))

print("\nSelfTrainingClassifier Accuracy Score:", accuracy_score(y_test, y_pred_st))

plt.figure(figsize=(8, 6))
sns.heatmap(confusion_matrix(y_test, y_pred_st), annot=True, fmt='d', cmap='Blues')
plt.title('SelfTrainingClassifier Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

Kmeans = KMeans(n_clusters=2, random_state=42)

Kmeans.fit(X_train)  # KMeans no supervisado, no usa y_train

y_pred_km = Kmeans.predict(X_test)

print("KMeans Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_km))

print("\nKMeans Classification Report:")
print(classification_report(y_test, y_pred_km))

print("\nKMeans Accuracy Score:", accuracy_score(y_test, y_pred_km))

plt.figure(figsize=(8, 6))
sns.heatmap(confusion_matrix(y_test, y_pred_km), annot=True, fmt='d', cmap='Blues')
plt.title('KMeans Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

from imblearn.over_sampling import RandomOverSampler

# Balancear las clases remuestreando los datos de entrenamiento
ros = RandomOverSampler(random_state=42)
X_train_balanced, y_train_balanced = ros.fit_resample(X_train, y_train)

MLP_classifier = MLPClassifier(
    hidden_layer_sizes=(100, 50),  # Dos capas ocultas
    activation='relu',             # Función de activación
    solver='adam',                 # Optimizador
    max_iter=500,                  # Más iteraciones
    random_state=42,
    early_stopping=True,           # Parar si no mejora
    validation_fraction=0.1,       # Validación interna
    learning_rate_init=0.001       # Tasa de aprendizaje inicial
)

# Entrenar con los datos balanceados
MLP_classifier.fit(X_train_balanced, y_train_balanced)
y_pred_mlpc = MLP_classifier.predict(X_test)

print("MLP Classifier Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_mlpc))

print("\nMLP Classifier Classification Report:")
print(classification_report(y_test, y_pred_mlpc, zero_division=0))

print("\nMLP Classifier Accuracy Score:", accuracy_score(y_test, y_pred_mlpc))

plt.figure(figsize=(8, 6))
sns.heatmap(confusion_matrix(y_test, y_pred_mlpc), annot=True, fmt='d', cmap='Blues')
plt.title('MLP Classifier Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# ============================================================
# 2. MLPRegressor - Regresión
# ============================================================
from imblearn.over_sampling import RandomOverSampler
import numpy as np

ros = RandomOverSampler(random_state=42)
X_train_balanced, y_train_balanced = ros.fit_resample(X_train, y_train)

MLP_regressor = MLPRegressor(
    hidden_layer_sizes=(100, 50),  # Dos capas ocultas
    activation='relu',             # Función de activación
    solver='adam',                 # Optimizador
    max_iter=500,                  # Más iteraciones
    random_state=42,
    early_stopping=True,           # Parar si no mejora
    validation_fraction=0.1,       # Validación interna
    learning_rate_init=0.001       # Tasa de aprendizaje inicial
)

MLP_regressor.fit(X_train_balanced, y_train_balanced)
y_pred_mlpr = MLP_regressor.predict(X_test)

# Redondear y clipear para que las predicciones sean 0 o 1
y_pred_mlpr_rounded = np.clip(np.round(y_pred_mlpr).astype(int), 0, 1)

print("MLP Regressor Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_mlpr_rounded))

print("\nMLP Regressor Classification Report:")
print(classification_report(y_test, y_pred_mlpr_rounded, zero_division=0))

print("\nMLP Regressor Accuracy Score:", accuracy_score(y_test, y_pred_mlpr_rounded))

plt.figure(figsize=(8, 6))
sns.heatmap(confusion_matrix(y_test, y_pred_mlpr_rounded), annot=True, fmt='d', cmap='Blues')
plt.title('MLP Regressor Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""El resumen final seria que"""

from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score, accuracy_score, classification_report, confusion_matrix, roc_curve, auc
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# ============================================================
# 1. Normalización
# ============================================================
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# ============================================================
# 2. Modelo XGBoost
# ============================================================
xgb = XGBClassifier(
    n_estimators         = 500,
    max_depth            = 4,
    learning_rate        = 0.5,
    subsample            = 0.8,
    colsample_bytree     = 0.8,
    scale_pos_weight     = len(y_train[y_train==0]) / len(y_train[y_train==1]),
    eval_metric          = 'auc',
    random_state         = 42,
    early_stopping_rounds= 20,
    verbosity            = 0
)

xgb.fit(
    X_train_scaled, y_train,
    eval_set = [(X_test_scaled, y_test)],
    verbose  = False
)

print(f"✅ Mejor número de árboles: {xgb.best_iteration}")

# ============================================================
# 3. Predicciones con umbral óptimo
# ============================================================
y_prob_xgb = xgb.predict_proba(X_test_scaled)[:, 1]

fpr, tpr, thresholds = roc_curve(y_test, y_prob_xgb)
optimal_idx       = np.argmax(tpr - fpr)
optimal_threshold = thresholds[optimal_idx]
print(f"✅ Umbral óptimo: {optimal_threshold:.4f}")

y_pred_xgb = (y_prob_xgb >= optimal_threshold).astype(int)

# ============================================================
# 4. Métricas
# ============================================================
print("\n" + "="*50)
print("XGBoost - Resultados")
print("="*50)
print(f"AUC:      {roc_auc_score(y_test, y_prob_xgb):.4f}")
print(f"Accuracy: {accuracy_score(y_test, y_pred_xgb):.4f}")
print(f"\nConfusion Matrix:\n{confusion_matrix(y_test, y_pred_xgb)}")
print(f"\nClassification Report:\n{classification_report(y_test, y_pred_xgb, zero_division=0)}")

# ============================================================
# 5. Gráficas
# ============================================================
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Confusion Matrix
sns.heatmap(confusion_matrix(y_test, y_pred_xgb),
            annot=True, fmt='d', cmap='Blues', ax=axes[0])
axes[0].set_title('XGBoost Confusion Matrix')
axes[0].set_xlabel('Predicted')
axes[0].set_ylabel('True')

# Curva ROC
roc_auc = auc(fpr, tpr)
axes[1].plot(fpr, tpr, color='darkorange', lw=2, label=f'AUC = {roc_auc:.4f}')
axes[1].plot([0,1], [0,1], 'k--', label='Random')
axes[1].axvline(x=fpr[optimal_idx], color='red', linestyle='--',
                label=f'Umbral óptimo = {optimal_threshold:.2f}')
axes[1].set_title('Curva ROC')
axes[1].set_xlabel('False Positive Rate')
axes[1].set_ylabel('True Positive Rate')
axes[1].legend()

# Importancia de features
feat_imp = xgb.feature_importances_
feat_names = X.columns
sorted_idx = np.argsort(feat_imp)
axes[2].barh(feat_names[sorted_idx], feat_imp[sorted_idx], color='steelblue')
axes[2].set_title('Importancia de Features')
axes[2].set_xlabel('Importancia')

plt.tight_layout()
plt.show()

"""El techo real del dataset con estas 6 features es AUC ≈ 0.70
Ningún modelo, por complejo que sea, va a superarlo significativamente.

# Por ultimo vamos a probar a implementar algoritmos geneticos para encontrar una solucion optima de este XGBClassifier
"""

from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score, accuracy_score, classification_report, confusion_matrix, roc_curve, auc
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import random
import time

# ============================================================
# 1. Normalización
# ============================================================
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# ============================================================
# 2. Espacio de búsqueda de hiperparámetros
# ============================================================
PARAM_SPACE = {
    'n_estimators'    : [25, 50, 100, 150, 200, 300, 400, 500],
    'max_depth'       : [2, 3, 4, 5, 6, 7, 8, 9, 10],
    'learning_rate'   : [0.01, 0.03, 0.05, 0.07, 0.1, 0.15, 0.2],
    'subsample'       : [0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0],
    'colsample_bytree': [0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
    'min_child_weight': [1, 3, 5, 7, 10],
    'gamma'           : [0, 0.1, 0.2, 0.3, 0.5, 1.0],
    'reg_alpha'       : [0, 0.01, 0.1, 0.5, 1.0],
    'reg_lambda'      : [0.5, 1.0, 1.5, 2.0, 5.0],
}

# ============================================================
# 3. Funciones del algoritmo genético
# ============================================================

def create_individual():
    """Crea un individuo aleatorio (conjunto de hiperparámetros)"""
    return {param: random.choice(values) for param, values in PARAM_SPACE.items()}

def fitness(individual, cv=3):
    """Evalúa un individuo con cross-validation → AUC"""
    model = XGBClassifier(
        **individual,
        scale_pos_weight = len(y_train[y_train==0]) / len(y_train[y_train==1]),
        eval_metric      = 'auc',
        random_state     = 42,
        verbosity        = 0,
        use_label_encoder= False
    )
    scores = cross_val_score(model, X_train_scaled, y_train,
                             cv=cv, scoring='roc_auc', n_jobs=-1)
    return scores.mean()

def selection(population, fitnesses, k=3):
    """Selección por torneo: elige el mejor de k individuos aleatorios"""
    tournament = random.sample(list(zip(population, fitnesses)), k)
    return max(tournament, key=lambda x: x[1])[0]

def crossover(parent1, parent2):
    """Cruce: cada hiperparámetro viene de uno de los dos padres aleatoriamente"""
    child = {}
    for param in PARAM_SPACE.keys():
        child[param] = parent1[param] if random.random() < 0.5 else parent2[param]
    return child

def mutate(individual, mutation_rate=0.2):
    """Mutación: cambia aleatoriamente algunos hiperparámetros"""
    mutated = individual.copy()
    for param, values in PARAM_SPACE.items():
        if random.random() < mutation_rate:
            mutated[param] = random.choice(values)
    return mutated

# ============================================================
# 4. Algoritmo Genético principal
# ============================================================
def genetic_algorithm(
    population_size = 15,   # Individuos por generación
    generations     = 10,    # Número de generaciones
    mutation_rate   = 0.2,  # Probabilidad de mutación
    elitism         = 2,    # Mejores individuos que pasan directamente
    cv              = 3     # Folds de cross-validation
):
    print("🧬 Iniciando Algoritmo Genético")
    print(f"   Población: {population_size} | Generaciones: {generations} | "
          f"Mutación: {mutation_rate} | Elitismo: {elitism}")
    print("="*60)

    # Historial para gráficas
    history = {
        'best_fitness'  : [],
        'mean_fitness'  : [],
        'worst_fitness' : []
    }

    # Población inicial aleatoria
    population = [create_individual() for _ in range(population_size)]
    best_individual = None
    best_fitness    = -np.inf

    start_time = time.time()

    for gen in range(generations):
        gen_start = time.time()
        print(f"\n🔄 Generación {gen+1}/{generations}")

        # Evaluar fitness de cada individuo
        fitnesses = []
        for i, ind in enumerate(population):
            f = fitness(ind, cv=cv)
            fitnesses.append(f)
            print(f"   Individuo {i+1:2d}/{population_size} → AUC: {f:.4f} | "
                  f"params: depth={ind['max_depth']}, "
                  f"lr={ind['learning_rate']}, "
                  f"n_est={ind['n_estimators']}")

        # Estadísticas de la generación
        gen_best  = max(fitnesses)
        gen_mean  = np.mean(fitnesses)
        gen_worst = min(fitnesses)

        history['best_fitness'].append(gen_best)
        history['mean_fitness'].append(gen_mean)
        history['worst_fitness'].append(gen_worst)

        # Actualizar mejor global
        best_idx = np.argmax(fitnesses)
        if fitnesses[best_idx] > best_fitness:
            best_fitness    = fitnesses[best_idx]
            best_individual = population[best_idx].copy()

        gen_time = time.time() - gen_start
        print(f"\n   📊 Gen {gen+1} → Best: {gen_best:.4f} | "
              f"Mean: {gen_mean:.4f} | Worst: {gen_worst:.4f} | "
              f"Tiempo: {gen_time:.1f}s")
        print(f"   🏆 Mejor global hasta ahora: {best_fitness:.4f}")

        # Nueva generación
        if gen < generations - 1:
            # Elitismo: los mejores pasan directamente
            sorted_pop = [x for _, x in sorted(zip(fitnesses, population),
                                               key=lambda x: x[0], reverse=True)]
            new_population = sorted_pop[:elitism]

            # Rellenar con cruce y mutación
            while len(new_population) < population_size:
                parent1 = selection(population, fitnesses)
                parent2 = selection(population, fitnesses)
                child   = crossover(parent1, parent2)
                child   = mutate(child, mutation_rate)
                new_population.append(child)

            population = new_population

    total_time = time.time() - start_time
    print(f"\n✅ Algoritmo genético completado en {total_time/60:.1f} minutos")
    print(f"🏆 Mejor AUC (CV): {best_fitness:.4f}")
    print(f"🔧 Mejores hiperparámetros encontrados:")
    for k, v in best_individual.items():
        print(f"   {k:20s}: {v}")

    return best_individual, best_fitness, history

# ============================================================
# 5. Ejecutar el algoritmo genético
# ============================================================
best_params, best_cv_auc, history = genetic_algorithm()


# ============================================================
# 6. Entrenar modelo final con los mejores hiperparámetros
# ============================================================
print("\n" + "="*60)
print("🚀 Entrenando modelo final con mejores hiperparámetros...")
print("="*60)

best_xgb = XGBClassifier(
    **best_params,
    scale_pos_weight     = len(y_train[y_train==0]) / len(y_train[y_train==1]),
    eval_metric          = 'auc',
    random_state         = 42,
    early_stopping_rounds= 20,
    verbosity            = 0
)

best_xgb.fit(
    X_train_scaled, y_train,
    eval_set = [(X_test_scaled, y_test)],
    verbose  = False
)

# Umbral óptimo
y_prob_best = best_xgb.predict_proba(X_test_scaled)[:, 1]
fpr, tpr, thresholds = roc_curve(y_test, y_prob_best)
optimal_idx       = np.argmax(tpr - fpr)
optimal_threshold = thresholds[optimal_idx]
y_pred_best       = (y_prob_best >= optimal_threshold).astype(int)

print(f"\nAUC Test:       {roc_auc_score(y_test, y_prob_best):.4f}")
print(f"Accuracy Test:  {accuracy_score(y_test, y_pred_best):.4f}")
print(f"Umbral óptimo:  {optimal_threshold:.4f}")
print(f"\nConfusion Matrix:\n{confusion_matrix(y_test, y_pred_best)}")
print(f"\nClassification Report:\n{classification_report(y_test, y_pred_best, zero_division=0)}")

# ============================================================
# 7. Gráficas
# ============================================================
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Evolución del algoritmo genético
axes[0, 0].plot(history['best_fitness'],  marker='o', label='Mejor',  color='green')
axes[0, 0].plot(history['mean_fitness'],  marker='s', label='Media',  color='blue')
axes[0, 0].plot(history['worst_fitness'], marker='^', label='Peor',   color='red')
axes[0, 0].set_title('Evolución del Algoritmo Genético')
axes[0, 0].set_xlabel('Generación')
axes[0, 0].set_ylabel('AUC (CV)')
axes[0, 0].legend()
axes[0, 0].grid(True, alpha=0.3)

# Confusion Matrix
sns.heatmap(confusion_matrix(y_test, y_pred_best),
            annot=True, fmt='d', cmap='Blues', ax=axes[0, 1])
axes[0, 1].set_title('Confusion Matrix - XGBoost Genético')
axes[0, 1].set_xlabel('Predicted')
axes[0, 1].set_ylabel('True')

# Curva ROC
roc_auc_val = auc(fpr, tpr)
axes[1, 0].plot(fpr, tpr, color='darkorange', lw=2, label=f'AUC = {roc_auc_val:.4f}')
axes[1, 0].plot([0, 1], [0, 1], 'k--', label='Random')
axes[1, 0].axvline(x=fpr[optimal_idx], color='red', linestyle='--',
                   label=f'Umbral = {optimal_threshold:.2f}')
axes[1, 0].set_title('Curva ROC')
axes[1, 0].set_xlabel('False Positive Rate')
axes[1, 0].set_ylabel('True Positive Rate')
axes[1, 0].legend()

# Importancia de features
feat_imp    = best_xgb.feature_importances_
feat_names  = X.columns
sorted_idx  = np.argsort(feat_imp)
axes[1, 1].barh(feat_names[sorted_idx], feat_imp[sorted_idx], color='steelblue')
axes[1, 1].set_title('Importancia de Features - Mejor XGBoost')
axes[1, 1].set_xlabel('Importancia')

plt.tight_layout()
plt.show()
